// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCslRE1j1qGlQpybhnq1V1zzdNQoVlNc2Y',
    appId: '1:25547624227:web:23b61db7ba7ce44e480696',
    messagingSenderId: '25547624227',
    projectId: 'transmaa-99c07',
    authDomain: 'transmaa-99c07.firebaseapp.com',
    storageBucket: 'transmaa-99c07.appspot.com',
    measurementId: 'G-C16PVMGK5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmFrtBFjtOX0bfKLvoWHO3ykJQVb7cmyo',
    appId: '1:25547624227:android:88f32702866d01c4480696',
    messagingSenderId: '25547624227',
    projectId: 'transmaa-99c07',
    storageBucket: 'transmaa-99c07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkDtFZPoEye6cyjBbM_LEiWTq_S7wXFw',
    appId: '1:25547624227:ios:778f715814fbb6ca480696',
    messagingSenderId: '25547624227',
    projectId: 'transmaa-99c07',
    storageBucket: 'transmaa-99c07.appspot.com',
    iosBundleId: 'com.example.sas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkDtFZPoEye6cyjBbM_LEiWTq_S7wXFw',
    appId: '1:25547624227:ios:3857464dfe7b5f91480696',
    messagingSenderId: '25547624227',
    projectId: 'transmaa-99c07',
    storageBucket: 'transmaa-99c07.appspot.com',
    iosBundleId: 'com.example.sas.RunnerTests',
  );
}
